### ISSUE TITLE
Foundry 08x readiness checklist

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-carousel#69]
Bug Fixes:
- [x] Carousel doesn't render
- [x] Initiative doesn't roll
- [x] Disposition colour not showing
- [x] Effects not displayed
- [x] Effects in wrong position
- [x] Combat controls missing
- [x] Control token on card click
- [x] Mass Initiative controls don't work
- [x] Overlay config doesn't open
- [x] ~~Fails to detect encounter without scene~~ not possible in core UI anyway
- [x] ~~Doesn't render properly with multi-scene Combats~~ not possible in core UI anyway
- [x] Doesn't rerender on Scene change
- [x] Doesn't correctly rerender if Combat is created while CC is already rendered
- [x] Toggle combatant visibility doesn't work

Enhancements:
- [x] ~~Add an indicator that a combatant is from a different scene~~ not possible in core UI anyway

Notes:
- Get token documents via scene instead of canvas
